### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [games647/CraftAPI#2]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/com/github/games647/craftapi/model/skin/SkinProperty.java: Line number => 56: API name => Signature:First parameter (with value "SHA1withRSA") should be any of {NONEwithDSA, SHA1withDSA, SHA224withDSA, SHA256withDSA, SHA256withRSA, SHA256withECDSA}<BR> File name => src/main/java/com/github/games647/craftapi/model/skin/SkinProperty.java: Line number => 66: API name => Signature:<BR>

**Comment by games647** [comment]
What is the problem with SHA1withRSA? It's a valid signature algorithm according to the JavaDoc: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/security/Signature.html

**Comment by mhp0rtal** [comment]
Hi,
Thanks for your attention.
I reported the cryptographic misuses due to my recent research on how developers employ Java Cryptography Architecture (JCA) APIs in Java applications. I utilized some static analysis tools intended for checking cryptographic practices. The aforementioned misuses in those files were obtained from the results of the tools. The severity of the bug is relative. For instance, Even though MD5 is listed on Java documentation, MD5 is not recommended to use in any language anymore as it is considered insecure. An attacker can try billions of candidate passwords per second on a single GPU. Nevertheless, depending on the scenario the same hash algorithm may not be a problem for file integrity purpose.
There are several instances of cryptographic misuses which could lead to a security vulnerability:
*Do not use ECB mode for encryption.
*Do not use a non-random IV for CBC encryption
*Do not use constant encryption keys.
*Do not use constant salts for PBE.
*Do not use fewer than 1,000 iterations for PBE.
*Do not use static seeds to seed SecureRandom(·)
You can try using either CryptoLint or CogniCrypt to check your code from a cryptographic point of view
Yes, you are right. 
Although many algorithms are listed on JavaDoc, some are proven that are vulnerable.
Unfortunately, It does not guarantee that the usage of the algorithm is considered to be safe.
